[package]
name = "giveaway"
version = "0.1.0"
authors = ["Vyacheslav Konovalov <crabvk@protonmail.com>"]
edition = "2018"

[dependencies]
concordium-std = "0.4"

[lib]
crate-type = ["cdylib", "rlib"]
